import "server-only";
import { z } from "zod";

import { auth } from "@/lib/auth";
import { ALL_STATUSES } from "@/lib/scope";
import { BodySchema, CreateStorySchema, LIST_LIMIT_DEFAULT, LIST_LIMIT_MAX, ReasonSchema } from "@/lib/stories";
import { NOTIFICATION_LIMIT_MAX } from "@/lib/notifications";

/**
 * The OpenAPI document, assembled at request time.
 *
 * Two halves, joined here:
 *
 *   - **The app's own endpoints**, described below. Their request shapes are
 *     not typed out twice: `z.toJSONSchema` converts the very Zod schemas the
 *     handlers validate with, so the document cannot promise a rule the server
 *     does not enforce, or miss one it does. Change `WishSchema` and the
 *     upload's documented body changes with it.
 *   - **Better Auth's endpoints**, generated by the library from its own
 *     router. It knows its own surface — sign-in, sign-up, session, passkey,
 *     reset, the admin plugin — and that surface moves when a plugin is added
 *     or a version is bumped. Copying it by hand would be a second source of
 *     truth with a shorter shelf life than the first.
 *
 *     This is called **in process**, never over HTTP. The `openAPI()` plugin
 *     that provides it also mounts `/api/auth/open-api/generate-schema`, and
 *     that endpoint answers 200 to anybody with no session — it would hand a
 *     stranger the list of which auth plugins this deployment runs and every
 *     path they expose, while the app's own document next door sits behind a
 *     session. Middleware answers 404 for it; see `src/middleware.ts`.
 *     (Importing the generator function directly would have avoided mounting
 *     anything, but Better Auth 1.7.1 declares that export in its types and
 *     does not actually re-export it at runtime.)
 *
 * Assembled per request rather than at build time because the server URL and
 * the session cookie's name both come from the deployment's environment, and
 * `next build` runs without it.
 */

/** OpenAPI 3.1 is a JSON Schema 2020-12 dialect, so this is a lift, not a translation. */
function jsonSchema(schema: z.ZodType): Record<string, unknown> {
  const converted = z.toJSONSchema(schema, {
    io: "input",
    unrepresentable: "any",
  }) as Record<string, unknown>;
  // `$schema` is legal in a JSON Schema document and noise in a components
  // entry — every tool already knows the dialect from `openapi: "3.1.0"`.
  delete converted.$schema;
  return converted;
}

const ERROR = {
  type: "object",
  required: ["error"],
  properties: {
    error: {
      type: "string",
      description: "One sentence, written for a person to read.",
      examples: ["Sign in first."],
    },
  },
} as const;

const errorResponse = (description: string) => ({
  description,
  content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
});

/** The refusals every authenticated endpoint can answer with. */
const COMMON_ERRORS = {
  "401": errorResponse("No session, or the account has been suspended."),
  "500": errorResponse("Something went wrong at our end. The message never carries detail."),
};

const STORY_SCHEMA = {
  type: "object",
  description:
    "A print request, filed from a pasted model link rather than an upload. " +
    "The Bambuddy handoff ids — library file, pipeline run, queue item, " +
    "archive — are deliberately absent: they're sync plumbing (see " +
    "src/lib/bambuddy-sync.ts), not this API's business. `status` and " +
    "`errorMessage` are what a caller needs instead.",
  required: ["id", "ref", "title", "status", "model", "color", "uploader"],
  properties: {
    id: { type: "integer", examples: [4] },
    ref: {
      type: "string",
      description: "The display reference, `PPP-` + (100 + id). What people paste into chat.",
      examples: ["PPP-104"],
    },
    title: { type: "string", examples: ["Cable clip"] },
    status: {
      type: "string",
      enum: [...ALL_STATUSES],
      description:
        "Requested -> Slicing -> Ready -> Printing -> Done is the happy path, " +
        "derived from Bambuddy's own state, not moved by hand. Failed and " +
        "Declined are branches off it, not steps on it.",
    },
    flagged: { type: "boolean" },
    flagReason: { type: ["string", "null"] },
    quantity: { type: "integer", minimum: 1 },
    neededBy: { type: ["string", "null"], format: "date-time" },
    model: {
      type: "object",
      description: "The pasted link, and what Bambuddy resolved it to.",
      properties: {
        url: { type: "string", examples: ["https://makerworld.com/en/models/123456"] },
        resolvedTitle: { type: ["string", "null"], examples: ["Cable clip, 4 mm"] },
      },
    },
    material: {
      type: ["string", "null"],
      description: "Whatever Bambuddy's spool reported at intake — not a fixed list.",
      examples: ["PLA Basic"],
    },
    color: {
      type: "object",
      description: "Snapshotted from a live spool at intake — see `spoolId` on the create request.",
      properties: {
        name: { type: "string", examples: ["Glow in Dark (Green)"] },
        hex: { type: ["string", "null"], examples: ["EBF1E0FF"] },
      },
    },
    tip: {
      type: "string",
      description:
        "The benefit offered, as its label when the request was made. `\"\"` when " +
        "nothing was offered, and always `\"\"` while the printer owner has the " +
        "tip jar switched off — the stored value is kept, not shown.",
      examples: ["A beer"],
    },
    note: { type: "string" },
    errorMessage: {
      type: ["string", "null"],
      description:
        "Bambuddy's own explanation, surfaced as-is: why a Requested ticket " +
        "hasn't started slicing, or why a Ready one hasn't auto-started " +
        "(a waiting_reason, not necessarily a failure).",
    },
    uploader: {
      type: "object",
      description: "Name and initials only. The address is not on the wire.",
      properties: {
        id: { type: "string" },
        name: { type: "string", examples: ["Ayla Berg"] },
        initials: { type: "string", examples: ["AB"] },
      },
    },
    commentCount: { type: "integer" },
    createdAt: { type: "string", format: "date-time" },
    updatedAt: { type: "string", format: "date-time" },
  },
} as const;

const COMMENT_SCHEMA = {
  type: "object",
  properties: {
    id: { type: "string" },
    storyId: { type: "integer" },
    ref: { type: "string", examples: ["PPP-104"] },
    body: { type: "string" },
    author: {
      type: "object",
      properties: {
        id: { type: "string" },
        name: { type: "string" },
        initials: { type: "string" },
        role: { type: "string", enum: ["client", "admin"] },
      },
    },
    createdAt: { type: "string", format: "date-time" },
  },
} as const;

const NOTIFICATION_SCHEMA = {
  type: "object",
  properties: {
    id: { type: "string" },
    storyId: { type: ["integer", "null"] },
    ref: {
      type: ["string", "null"],
      description: "Null once the ticket it referred to has been withdrawn.",
    },
    text: { type: "string" },
    read: { type: "boolean" },
    createdAt: { type: "string", format: "date-time" },
  },
} as const;

const storyIdParam = {
  name: "id",
  in: "path",
  required: true,
  description: "The numeric story id — `4`, not `PPP-104`.",
  schema: { type: "integer", minimum: 1 },
} as const;

const storyResponse = (description: string, extra: Record<string, unknown> = {}) => ({
  description,
  content: {
    "application/json": {
      schema: {
        type: "object",
        properties: { story: { $ref: "#/components/schemas/Story" }, ...extra },
      },
    },
  },
});

/**
 * Better Auth's half, re-based.
 *
 * The plugin describes its endpoints relative to its own mount point — it
 * emits `/sign-in/username`, because that is the path it sees. In this app
 * everything hangs off the catch-all at `/api/auth`, so each path is prefixed
 * on the way in. Its tags are prefixed too, so the console groups the sixty-odd
 * auth endpoints together instead of scattering them through the app's own.
 */
async function authPaths(): Promise<{
  paths: Record<string, unknown>;
  schemas: Record<string, unknown>;
  tags: { name: string; description: string }[];
}> {
  try {
    const spec = await auth.api.generateOpenAPISchema();
    const paths: Record<string, unknown> = {};

    for (const [path, item] of Object.entries(spec.paths ?? {})) {
      const operations = item as Record<string, { tags?: string[] } | undefined>;
      for (const operation of Object.values(operations)) {
        if (operation && Array.isArray(operation.tags)) {
          operation.tags = operation.tags.map((t) => `auth · ${t}`);
        }
      }
      paths[`/api/auth${path}`] = item;
    }

    return {
      paths,
      schemas: (spec.components?.schemas ?? {}) as Record<string, unknown>,
      tags: (spec.tags ?? []).map((t) => ({
        name: `auth · ${t.name}`,
        description: t.description,
      })),
    };
  } catch (error) {
    // A document missing its auth half is far better than no document at all —
    // and silently returning half of one is exactly the quiet failure this
    // repo tries to avoid, so it is logged and said out loud in the tag.
    console.error("[openapi] Better Auth schema unavailable", error);
    return {
      paths: {},
      schemas: {},
      tags: [
        {
          name: "auth · unavailable",
          description:
            "Better Auth's schema could not be generated for this request — " +
            "see the server log. The endpoints still exist under /api/auth.",
        },
      ],
    };
  }
}

export async function buildOpenApiDocument() {
  const baseURL = process.env.BETTER_AUTH_URL ?? "http://localhost:3000";
  const secure = baseURL.startsWith("https://");
  // Better Auth composes this from `advanced.cookiePrefix`, and prefixes it
  // with `__Secure-` when the cookies are Secure. Naming it correctly is what
  // lets a tool send the right one.
  const sessionCookie = `${secure ? "__Secure-" : ""}ppp.session_token`;

  const authHalf = await authPaths();

  return {
    openapi: "3.1.0",
    info: {
      title: "Pretty Please Print",
      version: process.env.PPP_TAG ?? "0.1.0",
      description:
        "The HTTP surface of one office's 3D-print queue.\n\n" +
        "**Everything except `/api/health` needs a session.** There is no " +
        "public sign-up: an account exists only where an invitation was " +
        "accepted, so start at `POST /api/auth/sign-in/username` with " +
        "credentials you already have.\n\n" +
        "Two ways to carry that session:\n\n" +
        "- **A cookie**, which the browser you are reading this in already " +
        "holds — Try it out below just works.\n" +
        `- **A bearer token.** Sign-in answers with a \`set-auth-token\` ` +
        "header; send it back as `Authorization: Bearer <token>`. It *is* the " +
        "session token, so signing out revokes it, and it does not belong in " +
        "a shell history you keep.\n\n" +
        "**Scope.** A client sees their own requests; the printer owner sees " +
        "every one. Asking for a ticket outside your scope is answered `404`, " +
        "not `403` — a `403` would confirm it exists. Being refused an " +
        "*action* is `403`, because these endpoints are listed on this page " +
        "and pretending they are missing would help nobody.",
      license: { name: "AGPL-3.0-or-later", identifier: "AGPL-3.0-or-later" },
    },
    servers: [{ url: baseURL, description: "This deployment." }],

    tags: [
      { name: "stories", description: "Print requests — the tickets on the board." },
      { name: "queue", description: "The printer owner's actions on a ticket." },
      { name: "conversation", description: "The thread that lives on a ticket." },
      { name: "activity", description: "Your notifications." },
      { name: "service", description: "Liveness, and this document." },
      ...authHalf.tags,
    ],

    components: {
      securitySchemes: {
        sessionCookie: {
          type: "apiKey",
          in: "cookie",
          name: sessionCookie,
          description:
            "The session cookie. HttpOnly, so a browser sends it for you and " +
            "no script can read it — including this page's.",
        },
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          description:
            "The session token from `set-auth-token` on any sign-in response.",
        },
      },
      schemas: {
        Error: ERROR,
        Story: STORY_SCHEMA,
        Comment: COMMENT_SCHEMA,
        Notification: NOTIFICATION_SCHEMA,
        // Derived from the Zod schemas the handlers actually validate with.
        CreateStory: jsonSchema(CreateStorySchema),
        FlagReason: jsonSchema(z.object({ reason: ReasonSchema })),
        CommentBody: jsonSchema(z.object({ body: BodySchema })),
        ...authHalf.schemas,
      },
    },

    // Applies to every operation. `/api/health` overrides it with `security: []`.
    security: [{ sessionCookie: [] }, { bearerAuth: [] }],

    paths: {
      "/api/health": {
        get: {
          tags: ["service"],
          summary: "Can the app serve?",
          description:
            "Deliberately terse, and the only endpoint reachable without a " +
            "session: it says whether the app can serve, never what it " +
            "connects to or why a check failed.",
          security: [],
          responses: {
            "200": {
              description: "It can.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: { ok: { type: "boolean", const: true } },
                  },
                },
              },
            },
            "503": {
              description: "It cannot — the database did not answer.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: { ok: { type: "boolean", const: false } },
                  },
                },
              },
            },
          },
        },
      },

      "/api/openapi.json": {
        get: {
          tags: ["service"],
          summary: "This document",
          description:
            "Needs a session, like everything else. It describes an " +
            "invite-only app to the people already inside it.",
          responses: {
            "200": { description: "The OpenAPI 3.1 document." },
            ...COMMON_ERRORS,
          },
        },
      },

      "/api/stories": {
        get: {
          tags: ["stories"],
          summary: "List tickets",
          description:
            "Newest first. A client sees their own; the printer owner sees " +
            "every one. The filters can only narrow that set — none of them " +
            "can widen it.\n\n" +
            "Paging is a cursor, not an offset: pass the `nextCursor` from " +
            "the previous page as `before`. A row inserted mid-page therefore " +
            "cannot make one repeat or vanish.",
          parameters: [
            {
              name: "status",
              in: "query",
              description:
                "Repeat the parameter, or separate with commas. Omit for every status.",
              schema: { type: "array", items: { type: "string", enum: [...ALL_STATUSES] } },
              explode: true,
            },
            { name: "flagged", in: "query", schema: { type: "boolean" } },
            {
              name: "mine",
              in: "query",
              description:
                "Only your own requests. Changes nothing for a client, whose " +
                "scope is already that; narrows the printer owner to theirs.",
              schema: { type: "boolean" },
            },
            {
              name: "limit",
              in: "query",
              schema: {
                type: "integer",
                minimum: 1,
                maximum: LIST_LIMIT_MAX,
                default: LIST_LIMIT_DEFAULT,
              },
            },
            {
              name: "before",
              in: "query",
              description: "The `nextCursor` from the previous page.",
              schema: { type: "integer", minimum: 1 },
            },
          ],
          responses: {
            "200": {
              description: "A page of tickets.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      stories: { type: "array", items: { $ref: "#/components/schemas/Story" } },
                      nextCursor: {
                        type: ["integer", "null"],
                        description: "Null on the last page.",
                      },
                    },
                  },
                },
              },
            },
            "400": errorResponse("A filter did not parse."),
            ...COMMON_ERRORS,
          },
        },

        post: {
          tags: ["stories"],
          summary: "File a request from a model link",
          description:
            "A link, not a file — there is no multipart endpoint any more. " +
            "`spoolId` is the only way to name a colour: it's resolved against " +
            "live Bambuddy inventory server-side, and `material`/`color` on " +
            "the response are snapshotted from that spool at this moment, not " +
            "re-read from Bambuddy afterward.\n\n" +
            "Resolving the link, importing it and starting the standard-PLA " +
            "pipeline all happen synchronously here — the common case is the " +
            "response already shows `status: \"Slicing\"` or even `\"Ready\"`. " +
            "A Bambuddy hiccup doesn't fail this call: the ticket is still " +
            "created as `Requested` with `errorMessage` set, and a background " +
            "sync retries it (see src/lib/bambuddy-sync.ts).\n\n" +
            "`tip` is optional, and only means something while the printer " +
            "owner has the tip jar on: then it must be the label of an active " +
            "benefit (`400` otherwise). With the jar off it is ignored.",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/CreateStory" },
                example: {
                  title: "Cable clip",
                  modelUrl: "https://makerworld.com/en/models/123456",
                  spoolId: 15,
                  quantity: 1,
                },
              },
            },
          },
          responses: {
            "201": storyResponse("Filed."),
            "400": errorResponse("A field was missing or did not parse, the link isn't a MakerWorld model page, the spool isn't PLA, or the tip isn't an active benefit."),
            "409": errorResponse("That spoolId isn't in Bambuddy's live inventory any more."),
            "503": errorResponse("Bambuddy's inventory couldn't be reached to check the spool. Retry later."),
            ...COMMON_ERRORS,
          },
        },
      },

      "/api/stories/{id}": {
        get: {
          tags: ["stories"],
          summary: "One ticket",
          parameters: [storyIdParam],
          responses: {
            "200": {
              description: "The ticket.",
              content: {
                "application/json": { schema: { $ref: "#/components/schemas/Story" } },
              },
            },
            "404": errorResponse("No such ticket — or not one you may see. The two are indistinguishable on purpose."),
            ...COMMON_ERRORS,
          },
        },
        delete: {
          tags: ["stories"],
          summary: "Withdraw your own request",
          description:
            "Only the person who asked for it, and only before Bambuddy has " +
            "any state for it — `Requested` or `Declined`. Past that Bambuddy " +
            "holds a library file and possibly a queue item, and tearing " +
            "those down on withdrawal isn't something this app does yet; ask " +
            "the printer owner instead.\n\n" +
            "The conversation and notifications go with it. The audit row stays.",
          parameters: [storyIdParam],
          responses: {
            "200": {
              description: "Withdrawn.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      withdrawn: { type: "boolean", const: true },
                      id: { type: "integer" },
                      ref: { type: "string" },
                      wasStatus: { type: "string" },
                    },
                  },
                },
              },
            },
            "403": errorResponse("Yours to see, but not yours to withdraw."),
            "404": errorResponse("No such ticket, or not one you may see."),
            "409": errorResponse("Already being worked on (ask the printer owner), or being handed to Bambuddy right now (try again in a minute)."),
            ...COMMON_ERRORS,
          },
        },
      },

      "/api/stories/{id}/decline": {
        post: {
          tags: ["queue"],
          summary: "Decline a request",
          description:
            "Terminal, and reachable only from `Requested`. There is no " +
            "endpoint that sets a ticket's status to a value you choose — " +
            "every status but `Declined` is derived from Bambuddy's own state " +
            "(see src/lib/bambuddy-sync.ts), not set directly. Once a request " +
            "has reached Bambuddy, saying no is a conversation and a " +
            "withdrawal, not a status change.",
          parameters: [storyIdParam],
          responses: {
            "200": storyResponse("Declined, and the uploader was told.", {
              moved: {
                type: "object",
                properties: { from: { type: "string" }, to: { type: "string" } },
              },
              notified: { type: "string" },
            }),
            "403": errorResponse("Not the printer owner, or past the point where declining is honest."),
            "404": errorResponse("No such ticket."),
            "409": errorResponse("Being handed to Bambuddy right now. Try again in a minute."),
            ...COMMON_ERRORS,
          },
        },
      },

      "/api/stories/{id}/flag": {
        post: {
          tags: ["queue"],
          summary: "Flag a model problem",
          description:
            "Does **not** change the status. The ticket stays where it is and " +
            "carries a note saying why it cannot proceed as-is. The reason is " +
            "required — a flag with no explanation tells the person waiting " +
            "nothing they can act on.",
          parameters: [storyIdParam],
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/FlagReason" },
                example: { reason: "The walls are 0.3 mm — it will not survive the bed." },
              },
            },
          },
          responses: {
            "200": storyResponse("Flagged, and the uploader was told.", {
              reason: { type: "string" },
              notified: { type: "string" },
            }),
            "400": errorResponse("No reason, or one too short to be useful."),
            "403": errorResponse("Only the printer owner flags a model."),
            "404": errorResponse("No such ticket."),
            ...COMMON_ERRORS,
          },
        },
        delete: {
          tags: ["queue"],
          summary: "Clear a flag",
          description:
            "The way off. A flag with no way off is a dead end — the ticket " +
            "would carry \"needs a look\" long after the model was fixed.",
          parameters: [storyIdParam],
          responses: {
            "200": storyResponse("Cleared, and the uploader was told.", {
              notified: { type: "string" },
            }),
            "403": errorResponse("Only the printer owner clears a flag."),
            "404": errorResponse("No such ticket."),
            "409": errorResponse("That ticket is not flagged."),
            ...COMMON_ERRORS,
          },
        },
      },

      "/api/stories/{id}/comments": {
        get: {
          tags: ["conversation"],
          summary: "Read the thread",
          description: "Oldest first, the way the ticket page reads.",
          parameters: [storyIdParam],
          responses: {
            "200": {
              description: "The thread.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      comments: {
                        type: "array",
                        items: { $ref: "#/components/schemas/Comment" },
                      },
                    },
                  },
                },
              },
            },
            "404": errorResponse("No such ticket, or not one you may see."),
            ...COMMON_ERRORS,
          },
        },
        post: {
          tags: ["conversation"],
          summary: "Say something",
          description:
            "Both sides may write. The notification goes to the *other* side — " +
            "nobody needs telling about their own comment.",
          parameters: [storyIdParam],
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/CommentBody" },
                example: { body: "Could you do it in teal?" },
              },
            },
          },
          responses: {
            "201": {
              description: "Posted.",
              content: {
                "application/json": { schema: { $ref: "#/components/schemas/Comment" } },
              },
            },
            "400": errorResponse("Empty, or longer than a comment wants to be."),
            "404": errorResponse("No such ticket, or not one you may see."),
            ...COMMON_ERRORS,
          },
        },
      },

      "/api/notifications": {
        get: {
          tags: ["activity"],
          summary: "Your Activity feed",
          description:
            "Yours and only yours — there is no parameter naming a recipient, " +
            "because the session already does.",
          parameters: [
            { name: "unread", in: "query", schema: { type: "boolean" } },
            {
              name: "limit",
              in: "query",
              schema: {
                type: "integer",
                minimum: 1,
                maximum: NOTIFICATION_LIMIT_MAX,
                default: 25,
              },
            },
          ],
          responses: {
            "200": {
              description: "Newest first, with the count the header badge shows.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      notifications: {
                        type: "array",
                        items: { $ref: "#/components/schemas/Notification" },
                      },
                      unread: { type: "integer" },
                    },
                  },
                },
              },
            },
            "400": errorResponse("A filter did not parse."),
            ...COMMON_ERRORS,
          },
        },
      },

      "/api/notifications/read": {
        post: {
          tags: ["activity"],
          summary: "Mark read",
          description:
            "One notification with `{ \"id\": \"…\" }`, or the whole feed with " +
            "an empty body.\n\n" +
            "Somebody else's id is a no-op rather than a 404 — a 404 here " +
            "would be an oracle for whose notification is whose.",
          requestBody: {
            required: false,
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    id: {
                      type: "string",
                      description: "Leave it out to mark everything read.",
                    },
                  },
                },
              },
            },
          },
          responses: {
            "200": {
              description: "How many rows changed, and what is left unread.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      changed: { type: "integer" },
                      unread: { type: "integer" },
                    },
                  },
                },
              },
            },
            "400": errorResponse("`id` was present but not a string."),
            ...COMMON_ERRORS,
          },
        },
      },

      ...authHalf.paths,
    },
  };
}
