/**
 * Points the host-side tooling at the containerised stack.
 *
 *   npm run env:container
 *
 * The scripts in this repo (verify:*, probe:security, shots) run on the host
 * and read `.env`. When the app is running under docker-compose.prod.yml its
 * database and object store have generated credentials that live in
 * `.env.docker` — so `.env`, which describes the *dev* stack, cannot reach
 * them. That mismatch is silent and looks like an authentication failure.
 *
 * This rewrites `.env` from `.env.docker`, translating the in-network service
 * names to the ports the test overlay publishes on localhost. The previous
 * `.env` is kept as `.env.backup`.
 *
 * To go back to the host dev workflow: `npm run db:up` and restore .env.backup.
 */
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";

const SOURCE = ".env.docker";
const TARGET = ".env";

if (!existsSync(SOURCE)) {
  console.error(`${SOURCE} not found. Copy .env.docker.example first.`);
  process.exit(1);
}

const env = new Map<string, string>();
for (const line of readFileSync(SOURCE, "utf8").split("\n")) {
  const m = /^\s*([A-Z0-9_]+)\s*=\s*["']?([^"'\n#]*)["']?\s*$/.exec(line);
  if (m) env.set(m[1]!, m[2]!.trim());
}

const need = (key: string, fallback = "") => env.get(key) ?? fallback;

// Service names inside the compose network; localhost ports outside it.
const written = [
  `# Generated by \`npm run env:container\` — points host tooling at the`,
  `# running docker-compose stack. Re-run after changing .env.docker.`,
  `DATABASE_URL="postgresql://ppp:${need("DB_PASSWORD")}@localhost:5432/ppp?schema=public"`,
  `BETTER_AUTH_URL="${need("APP_URL", "http://localhost:3000")}"`,
  `BETTER_AUTH_SECRET="${need("BETTER_AUTH_SECRET")}"`,
  `ADMIN_EMAIL="${need("ADMIN_EMAIL")}"`,
  `ADMIN_NAME="${need("ADMIN_NAME")}"`,
  `MAIL_FROM="${need("MAIL_FROM")}"`,
  `SMTP_URL="smtp://localhost:1025"`,
  "",
].join("\n");

if (existsSync(TARGET)) copyFileSync(TARGET, `${TARGET}.backup`);
writeFileSync(TARGET, written);

console.info(
  `.env now points at the container stack (previous saved to ${TARGET}.backup).\n` +
    `  database  localhost:5432\n` +
    `  mail      localhost:1025 (Mailpit UI on :8025)`,
);
